# Generated by Django 3.2.21 on 2023-10-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_set_managed_to_true'),
        ('core', '0023_alter_jsonext_column_in_tblOfficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(db_column='StationID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=256, null=True)),
                ('location', models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
            ],
            options={
                'db_table': 'tblStation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='officer',
            name='station',
            field=models.ForeignKey(blank=True, db_column='StationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.station'),
        ),
    ]
