# Generated by Django 3.2.22 on 2023-11-30 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20231021_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='uuid',
            field=models.UUIDField(db_column='StationUUID', default=uuid.uuid4, unique=True),
        ),
    ]
