# Generated by Django 3.2.23 on 2023-12-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_station_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(blank=True, db_column='StationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.station'),
        ),
    ]
