# Generated by Django 3.2.21 on 2024-01-09 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('name', models.CharField(db_column='ConfigName', max_length=256)),
                ('model_name', models.CharField(db_column='ModelName', max_length=256)),
                ('model_id', models.CharField(db_column='ModelId', max_length=256)),
            ],
            options={
                'db_table': 'tblGenericConfig',
                'managed': True,
            },
        ),
    ]
