# Generated by Django 3.2.22 on 2024-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_genericconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('app_name', models.CharField(db_column='AppName', max_length=256)),
                ('model_name', models.CharField(db_column='ModelName', max_length=256)),
                ('action', models.CharField(db_column='Action', max_length=256)),
                ('new_obj_id', models.CharField(blank=True, db_column='NewObjID', max_length=256, null=True)),
                ('old_obj_id', models.CharField(blank=True, db_column='OldObjID', max_length=256, null=True)),
                ('changes', models.JSONField(blank=True, db_column='Changes', null=True)),
                ('audit_by_id', models.CharField(db_column='AuditByID', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='CreatedTime', null=True)),
            ],
            options={
                'db_table': 'tblAuditLogs',
                'managed': True,
            },
        ),
    ]
