# Generated by Django 3.2.21 on 2024-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auditlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='audit_for',
            field=models.CharField(db_column='AuditFor', max_length=256, null=True),
        ),
    ]
