# Generated by Django 3.2.21 on 2024-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auditlogs_audit_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
    ]
