# Generated by Django 3.2.21 on 2024-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auditlogs_json_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
