# Generated by Django 3.2.21 on 2024-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_interactiveuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_portal_user',
            field=models.BooleanField(db_column='IsPortalUser', default=False),
        ),
    ]
