# Generated by Django 3.2.21 on 2024-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_is_portal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveuser',
            name='fosa_emp_permissions',
            field=models.CharField(db_column='FosaEmpPermissions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interactiveuser',
            name='is_fosa_emp',
            field=models.BooleanField(db_column='IsFosaEmp', default=False),
        ),
    ]
