# Generated by Django 3.2.21 on 2024-06-14 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20240531_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamuNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=50, null=True)),
                ('message', models.TextField(db_column='Message')),
                ('is_read', models.BooleanField(db_column='IsRead', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created At')),
                ('redirect_url', models.CharField(blank=True, db_column='RedirectURL', max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='camu_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblCamuNotification',
                'managed': True,
            },
        ),
    ]
