# Generated by Django 3.2.25 on 2024-07-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_camunotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpApiFailedLogs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('module', models.CharField(db_column='Module', max_length=50, null=True)),
                ('action', models.CharField(db_column='Action', max_length=50, null=True)),
                ('response_status_code', models.IntegerField(db_column='ResponseCode', null=True)),
                ('response_json', models.JSONField(db_column='ResponseJson', null=True)),
                ('request_url', models.CharField(db_column='RequestURL', max_length=500, null=True)),
                ('message', models.TextField(db_column='Message', null=True)),
                ('request_data', models.JSONField(db_column='ProvidedData', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt', null=True)),
                ('resync_status', models.IntegerField(db_column='ResyncStatus', null=True)),
                ('resync_at', models.DateTimeField(db_column='ResyncAt', null=True)),
                ('created_by', models.ForeignKey(db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(db_column='Parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_erp_logs', to='core.erpapifailedlogs')),
                ('resync_by', models.ForeignKey(db_column='ResyncBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='erp_resync_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblErpFailedLogs',
                'managed': True,
            },
        ),
    ]
