# Generated by Django 3.2.21 on 2024-07-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_auto_20240710_1639'),
        ('payment', '0021_auto_20240722_1853'),
        ('location', '0021_auto_20240702_1757'),
        ('contract', '0023_auto_20240705_1228'),
        ('core', '0035_erpapifailedlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='contract',
            field=models.ForeignKey(db_column='Contract', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_erp_logs', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='health_facility',
            field=models.ForeignKey(db_column='HealthFacility', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_erp_logs', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='item',
            field=models.ForeignKey(db_column='Item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_erp_logs', to='medical.item'),
        ),
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='payment',
            field=models.ForeignKey(db_column='Payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_erp_logs', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='payment_penalty',
            field=models.ForeignKey(db_column='Penalty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='penalty_erp_logs', to='payment.paymentpenaltyandsanction'),
        ),
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='service',
            field=models.ForeignKey(db_column='Service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_erp_logs', to='medical.service'),
        ),
    ]
