# Generated by Django 3.2.25 on 2024-07-26 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20240725_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpapifailedlogs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
