# Generated by Django 3.2.25 on 2024-07-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0037_auto_20240716_1739'),
        ('core', '0036_auto_20240725_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='policy_holder',
            field=models.ForeignKey(db_column='PolicyHolder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.policyholder'),
        ),
    ]
