# Generated by Django 3.2.25 on 2024-08-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0033_auto_20240723_2018'),
        ('core', '0036_auto_20240725_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='claim',
            field=models.ForeignKey(db_column='Claim', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_erp_logs', to='claim.claim'),
        ),
        migrations.AddField(
            model_name='erpapifailedlogs',
            name='policy_holder',
            field=models.ForeignKey(db_column='PolicyHolder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policyholder_erp_logs', to='policyholder.policyholder'),
        ),
    ]
