# Generated by Django 3.2.21 on 2024-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20240805_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camunotification',
            name='message',
            field=models.JSONField(db_column='Message', null=True),
        ),
    ]
