# Generated by Django 3.2.21 on 2024-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_banks_historicalbanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fosa_user',
            field=models.BooleanField(db_column='IsFosaUser', default=False),
        ),
    ]
