# Generated by Django 3.2.21 on 2024-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_user_is_fosa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='is_default',
            field=models.BooleanField(db_column='IsDefault', default=False),
        ),
        migrations.AddField(
            model_name='erpoperations',
            name='is_default',
            field=models.BooleanField(db_column='IsDefault', default=False),
        ),
        migrations.AddField(
            model_name='historicalbanks',
            name='is_default',
            field=models.BooleanField(db_column='IsDefault', default=False),
        ),
        migrations.AddField(
            model_name='historicalerpoperations',
            name='is_default',
            field=models.BooleanField(db_column='IsDefault', default=False),
        ),
    ]
