# Generated by Django 3.2.25 on 2024-09-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20240909_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_path', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=50)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True)),
                ('hour_of_day', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tblScheduledTask',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=50)),
                ('output', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='core.scheduledtask')),
            ],
            options={
                'db_table': 'tblCronJobLog',
                'managed': True,
            },
        ),
    ]
