# Generated by Django 3.2.21 on 2024-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_cronjoblog_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='module',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='reference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
