# Generated by Django 3.2.25 on 2025-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20240925_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveuser',
            name='password_reset_token',
            field=models.CharField(blank=True, db_column='PasswordResetToken', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='interactiveuser',
            name='password_reset_token_expiration',
            field=models.DateTimeField(blank=True, db_column='PasswordResetTokenExpiration', null=True),
        ),
    ]
