# Generated by Django 3.2.25 on 2025-04-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0059_auto_20241226_0907'),
        ('core', '0047_userauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveuser',
            name='insuree_id',
            field=models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
    ]
